basePath: /api/v1
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: Sai Kris
    url: http://www.swagger.io/support
  description: This is a simple REST API written in Golang to demonstrate it's simplicity.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Web API written in Golang
  version: "1.0"
paths: {}
swagger: "2.0"
